--------------------------------------------------------
--  Fichier créé - mardi-mai-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence RENDEZVOUS_AUTO_INCR
--------------------------------------------------------

   CREATE SEQUENCE  "DADOU"."RENDEZVOUS_AUTO_INCR"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VISITE_AUTO_INC
--------------------------------------------------------

   CREATE SEQUENCE  "DADOU"."VISITE_AUTO_INC"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "DADOU"."CONGE" 
   (	"ID_CONGE" NUMBER, 
	"DEBUT_CONGE" DATE, 
	"FIN_CONGE" DATE, 
	"CIN_EMP" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "DADOU"."EMPLOYES" 
   (	"CIN_EMP" NUMBER, 
	"PRENOM_EMP" VARCHAR2(50 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"MOT_DE_PASSE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ID
--------------------------------------------------------

  CREATE TABLE "DADOU"."ID" 
   (	"IDENTIFIANT" NUMBER(*,0), 
	"MAIL_DESTINATAIRE" VARCHAR2(20 BYTE), 
	"SUJET" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SMS
--------------------------------------------------------

  CREATE TABLE "DADOU"."SMS" 
   (	"TEL" NUMBER(*,0), 
	"OBJET" VARCHAR2(20 BYTE), 
	"MESSAGE" VARCHAR2(20 BYTE), 
	"DATE_SMS" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAFFICS_DES_ACCIDENTS
--------------------------------------------------------

  CREATE TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" 
   (	"ID_ACCIDENT" NUMBER(*,0), 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"CIN_ACC" NUMBER, 
	"EMAIL_ACC" VARCHAR2(25 BYTE), 
	"TEL_ACC" NUMBER(*,0), 
	"NUM_MATRICULE" VARCHAR2(20 BYTE), 
	"DATE_ACCIDENT" DATE, 
	"ADRESSE_ACC" VARCHAR2(30 BYTE), 
	"VITESSE_ACC" NUMBER, 
	"INTENSITE_ACC" VARCHAR2(20 BYTE), 
	"ETAT_ACC" VARCHAR2(20 BYTE), 
	"ECLAIRAGE_ACC" VARCHAR2(20 BYTE), 
	"CONSE_ACC" VARCHAR2(20 BYTE), 
	"GENRE_ACC" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DADOU"."USERS" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"CODE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VIOLANCE_ARNAQUE
--------------------------------------------------------

  CREATE TABLE "DADOU"."VIOLANCE_ARNAQUE" 
   (	"ID_TRAFFIC" NUMBER, 
	"NOM_TRAFFIC" VARCHAR2(20 BYTE), 
	"PRENOM_TRAFFIC" VARCHAR2(20 BYTE), 
	"EMAIL_TRAFFIC" VARCHAR2(20 BYTE), 
	"CIN_TRAFFIC" NUMBER, 
	"TEL_TRAFFIC" NUMBER, 
	"NOM_ACCUSES" VARCHAR2(20 BYTE), 
	"AUTRE_TR" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DADOU.CONGE
SET DEFINE OFF;
REM INSERTING into DADOU.EMPLOYES
SET DEFINE OFF;
REM INSERTING into DADOU.ID
SET DEFINE OFF;
REM INSERTING into DADOU.SMS
SET DEFINE OFF;
REM INSERTING into DADOU.TRAFFICS_DES_ACCIDENTS
SET DEFINE OFF;
Insert into DADOU.TRAFFICS_DES_ACCIDENTS (ID_ACCIDENT,MATRICULE,CIN_ACC,EMAIL_ACC,TEL_ACC,NUM_MATRICULE,DATE_ACCIDENT,ADRESSE_ACC,VITESSE_ACC,INTENSITE_ACC,ETAT_ACC,ECLAIRAGE_ACC,CONSE_ACC,GENRE_ACC) values ('555','888','94533488','hh@esprit.tn','7',null,to_date('01/01/00','DD/MM/RR'),null,'0',null,null,null,null,null);
Insert into DADOU.TRAFFICS_DES_ACCIDENTS (ID_ACCIDENT,MATRICULE,CIN_ACC,EMAIL_ACC,TEL_ACC,NUM_MATRICULE,DATE_ACCIDENT,ADRESSE_ACC,VITESSE_ACC,INTENSITE_ACC,ETAT_ACC,ECLAIRAGE_ACC,CONSE_ACC,GENRE_ACC) values ('67','888','94533488','hh@esprit.tn','553488',null,to_date('01/01/00','DD/MM/RR'),null,'0',null,null,null,null,null);
Insert into DADOU.TRAFFICS_DES_ACCIDENTS (ID_ACCIDENT,MATRICULE,CIN_ACC,EMAIL_ACC,TEL_ACC,NUM_MATRICULE,DATE_ACCIDENT,ADRESSE_ACC,VITESSE_ACC,INTENSITE_ACC,ETAT_ACC,ECLAIRAGE_ACC,CONSE_ACC,GENRE_ACC) values ('1112','455Tunis 2020','123456','houda@esprit.tn','98653789','121Tunis 212',to_date('01/01/00','DD/MM/RR'),'ariana','0',null,null,null,null,'Route principale');
Insert into DADOU.TRAFFICS_DES_ACCIDENTS (ID_ACCIDENT,MATRICULE,CIN_ACC,EMAIL_ACC,TEL_ACC,NUM_MATRICULE,DATE_ACCIDENT,ADRESSE_ACC,VITESSE_ACC,INTENSITE_ACC,ETAT_ACC,ECLAIRAGE_ACC,CONSE_ACC,GENRE_ACC) values ('5555','1221','123456','hh','94533488',null,to_date('01/01/00','DD/MM/RR'),'tunis','0',null,null,null,null,null);
REM INSERTING into DADOU.USERS
SET DEFINE OFF;
Insert into DADOU.USERS (USERNAME,PASSWORD,TEL,CODE,EMAIL) values ('houda','123',null,null,null);
Insert into DADOU.USERS (USERNAME,PASSWORD,TEL,CODE,EMAIL) values ('zaineb','58','945','58','758');
REM INSERTING into DADOU.VIOLANCE_ARNAQUE
SET DEFINE OFF;
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('111','houda','koubaa','houda@','21214578','94533488',null,null,null);
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('88','houda','koubaa','houda.k@','1514247','94533488',null,null,'sexuelle');
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('1000','houda','koubaa','houda.k@','1514247','94533488',null,null,'psychologique');
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('78','houda',null,null,'0','0',null,null,'psychologique');
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('7877','houda',null,null,'0','0',null,null,'sexuelle');
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('57','mp',null,null,'88888','0',null,null,'physique');
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('750','dadou','koubaa',null,'0','0',null,null,'sexuelle');
Insert into DADOU.VIOLANCE_ARNAQUE (ID_TRAFFIC,NOM_TRAFFIC,PRENOM_TRAFFIC,EMAIL_TRAFFIC,CIN_TRAFFIC,TEL_TRAFFIC,NOM_ACCUSES,AUTRE_TR,TYPE) values ('15','houda','koubaa',null,'123456','94533488',null,null,null);
--------------------------------------------------------
--  DDL for Index CONGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DADOU"."CONGE_PK" ON "DADOU"."CONGE" ("ID_CONGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DADOU"."ID_PK" ON "DADOU"."ID" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DADOU"."EMPLOYES_PK" ON "DADOU"."EMPLOYES" ("CIN_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DADOU"."USERS_PK" ON "DADOU"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VIOLANCE_ARNAQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DADOU"."VIOLANCE_ARNAQUE_PK" ON "DADOU"."VIOLANCE_ARNAQUE" ("ID_TRAFFIC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRAFFICS_DES_ACCIDENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DADOU"."TRAFFICS_DES_ACCIDENTS_PK" ON "DADOU"."TRAFFICS_DES_ACCIDENTS" ("ID_ACCIDENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TRAFFICS_DES_ACCIDENTS
--------------------------------------------------------

  ALTER TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" MODIFY ("ID_ACCIDENT" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" MODIFY ("MATRICULE" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" MODIFY ("CIN_ACC" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" MODIFY ("EMAIL_ACC" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" MODIFY ("TEL_ACC" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."TRAFFICS_DES_ACCIDENTS" ADD CONSTRAINT "TRAFFICS_DES_ACCIDENTS_PK" PRIMARY KEY ("ID_ACCIDENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SMS
--------------------------------------------------------

  ALTER TABLE "DADOU"."SMS" MODIFY ("TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "DADOU"."CONGE" ADD CONSTRAINT "CONGE_PK" PRIMARY KEY ("ID_CONGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DADOU"."CONGE" MODIFY ("ID_CONGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VIOLANCE_ARNAQUE
--------------------------------------------------------

  ALTER TABLE "DADOU"."VIOLANCE_ARNAQUE" MODIFY ("ID_TRAFFIC" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."VIOLANCE_ARNAQUE" MODIFY ("NOM_TRAFFIC" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."VIOLANCE_ARNAQUE" ADD CONSTRAINT "VIOLANCE_ARNAQUE_PK" PRIMARY KEY ("ID_TRAFFIC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DADOU"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "DADOU"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "DADOU"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("CIN_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DADOU"."EMPLOYES" MODIFY ("CIN_EMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ID
--------------------------------------------------------

  ALTER TABLE "DADOU"."ID" ADD CONSTRAINT "ID_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DADOU"."ID" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "DADOU"."CONGE" ADD CONSTRAINT "FK" FOREIGN KEY ("CIN_EMP")
	  REFERENCES "DADOU"."EMPLOYES" ("CIN_EMP") ENABLE;
